### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by xantao** [vekat/markov-chainer#1]
Hi! First of all, thank for your work <3

I was guessing how to use the `tokens` parameter in the `run` function: do I need to send an array of strings, a whole string, or I need to build a token with `parseTokenString`? Couldn't understand how to use it as it is on the documentation.

Thanks in advance!

**Comment by vccortez** [comment]
hi @supng, no problem !

i had to re-read the code to understand this, it's been so long. i guess the documentation needs some work indeed, because it was not obvious to me either, but i got it.

basically, the idea here is that a token (any piece of JSONable data) is a unit of this markov process, or a state, and depending on the `order` you choose for the process, the tokens will be grouped into tuples of states. the theory explains that an `m`-order markov chain will determine the next state based on the `m`-th previous states. here, the `model` is just a map of tuples to possible next states.

so, the `tokens` parameter in the `run` function just represents the states from which you'd hope to start walking in the markov chain. they are just like the tokens you used to build a chain model (the single values in each line of your corpus).

a `tokenMap` is just a reverse map of tokens to state tuples. it basically maps single states (tokens) to all groups (tuples) that contain that state. this is only helpful when you are using a higher order chain (which means that your state tuples have more than one state), but you want to start the process from a single token instead of having to provide all tokens would that actually form a valid tuple of states in your model.

hope this helps clear it up a bit, feel free to ask for more clarification.
